### ISSUE TITLE
app gets closed on start-up

### ISSUE THREAD

**Issue by sjjh** [ZwS/keyrings#2]
If I try to start the app, it imeadetly closes and the error message '"Keyrings" was terminated.' (German original: '"Keyrings" wurde beendet') is shown. I do have my gnome keyring from Ubuntu 15.10 placed at "/storage/emulated/0/keyrings/". Deleting the app cache via the system settings didn't change anything. If I move the keyring folder somewhere else, I can start the app without problems.
Fairphone 2 running a self compiled Android 5.1

**Comment by ZwS** [comment]
Hi and thank you for bug report.
I just checked app on my Nexus 4 with android 5.1.1 and various keyrings and unable to reproduce crash. I think that logcat can give you a reason of crash. But I don't think that even if cause will be discovered I'll fix it. I dropped android learning and I'll need time to look into it again. But anyway, I'll be glad to accept any pull requests with fixes.

**Comment by sjjh** [comment]
I got the feeling that it might be connected to the name of a keyring (containing umlaute as äöü)
 I won't be able to debug the issue with a computer in the next 10 days, but will come back to you later.

**Comment by sjjh** [comment]
Sorry, it took me a little longer. I believe this is the relevant excerpt of the logcat:

`E/AndroidRuntime(12563): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(12563): Process: com.zws.keyrings, PID: 12563
E/AndroidRuntime(12563): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(12563):    at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(12563):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(12563):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(12563):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(12563):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(12563):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(12563):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(12563):    at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(12563): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1752462460 byte allocation with 4194304 free bytes and 127MB until OOM
E/AndroidRuntime(12563):    at com.zws.keyrings.jgkm.EncryptedKeyringParser.getString(EncryptedKeyringParser.java:189)
E/AndroidRuntime(12563):    at com.zws.keyrings.jgkm.EncryptedKeyringParser.readKeyringInfo(EncryptedKeyringParser.java:75)
E/AndroidRuntime(12563):    at com.zws.keyrings.jgkm.KeyringInfo.<init>(KeyringInfo.java:48)
E/AndroidRuntime(12563):    at com.zws.keyrings.MainActivity$ReadFilesTask.doInBackground(MainActivity.java:372)
E/AndroidRuntime(12563):    at com.zws.keyrings.MainActivity$ReadFilesTask.doInBackground(MainActivity.java:1)
E/AndroidRuntime(12563):    at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(12563):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(12563):    ... 4 more
W/ActivityManager( 1149):   Force finishing activity 1 com.zws.keyrings/.MainActivity`

I can send you the whole logcat via email if you want.

**Comment by ZwS** [comment]
This part of log is enough. Seems app write attribute information in wrong way and this cause file to be broken after saving. Even if you didn't change secret save method will be triggered and produce corrupt.

Issue occurs in saving of decrypted information about attributes. Next fields seems missing

> guint32 int_hash, or string str_hash

App doesn't save these hashes in attribute section of file.
I'll take a look on this issue, but I cannot guarantee that this will be fixed in the nearest future.

**Comment by sjjh** [comment]
Just a friendly check if you found time to look at the issue? I'm still looking for a solution to use my gnome keyring on my android. :)
